#!/bin/bash
# Setup Box.com configuration for transcript downloads
# Extracts BOX_CONFIG_JSON from mindprint-agent's .env.local file

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENT_DIR="$PROJECT_ROOT/../mindprint-agent"

echo "Setting up Box.com configuration for transcript downloads..."
echo ""

# Check if mindprint-agent .env.local exists
ENV_FILE="$AGENT_DIR/.env.local"
if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: mindprint-agent .env.local not found at: $ENV_FILE"
    echo "Please ensure mindprint-agent is in the expected location."
    exit 1
fi

# Extract BOX_CONFIG_JSON from .env.local
# Handle the case where it might be on one line or split across lines
BOX_CONFIG=$(grep "^BOX_CONFIG_JSON=" "$ENV_FILE" | sed 's/^BOX_CONFIG_JSON=//' | tr -d '\n')

if [ -z "$BOX_CONFIG" ]; then
    echo "ERROR: BOX_CONFIG_JSON not found in $ENV_FILE"
    exit 1
fi

# Validate JSON
if ! echo "$BOX_CONFIG" | python3 -m json.tool > /dev/null 2>&1; then
    echo "WARNING: BOX_CONFIG_JSON appears to be invalid JSON"
    echo "Attempting to fix..."
    
    # Try to extract just the JSON part (remove any trailing content)
    BOX_CONFIG=$(echo "$BOX_CONFIG" | python3 -c "
import sys
import json
import re

line = sys.stdin.read()
# Find JSON object
match = re.search(r'\{.*\}', line, re.DOTALL)
if match:
    try:
        json.loads(match.group(0))
        print(match.group(0))
    except:
        pass
")
fi

# Create .env file in mindprint-model if it doesn't exist
ENV_OUTPUT="$PROJECT_ROOT/.env"
if [ ! -f "$ENV_OUTPUT" ]; then
    echo "# Box.com Configuration for Transcript Downloads" > "$ENV_OUTPUT"
    echo "# Auto-generated by setup_box_config.sh" >> "$ENV_OUTPUT"
    echo "" >> "$ENV_OUTPUT"
fi

# Add or update BOX_CONFIG_JSON
if grep -q "^BOX_CONFIG_JSON=" "$ENV_OUTPUT" 2>/dev/null; then
    # Update existing
    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "s|^BOX_CONFIG_JSON=.*|BOX_CONFIG_JSON=$BOX_CONFIG|" "$ENV_OUTPUT"
    else
        # Linux
        sed -i "s|^BOX_CONFIG_JSON=.*|BOX_CONFIG_JSON=$BOX_CONFIG|" "$ENV_OUTPUT"
    fi
    echo "✓ Updated BOX_CONFIG_JSON in $ENV_OUTPUT"
else
    # Add new
    echo "BOX_CONFIG_JSON=$BOX_CONFIG" >> "$ENV_OUTPUT"
    echo "✓ Added BOX_CONFIG_JSON to $ENV_OUTPUT"
fi

# Also add to .env.local if it exists (for local development)
ENV_LOCAL="$PROJECT_ROOT/.env.local"
if [ -f "$ENV_LOCAL" ]; then
    if grep -q "^BOX_CONFIG_JSON=" "$ENV_LOCAL" 2>/dev/null; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^BOX_CONFIG_JSON=.*|BOX_CONFIG_JSON=$BOX_CONFIG|" "$ENV_LOCAL"
        else
            sed -i "s|^BOX_CONFIG_JSON=.*|BOX_CONFIG_JSON=$BOX_CONFIG|" "$ENV_LOCAL"
        fi
        echo "✓ Updated BOX_CONFIG_JSON in $ENV_LOCAL"
    else
        echo "" >> "$ENV_LOCAL"
        echo "# Box.com Configuration" >> "$ENV_LOCAL"
        echo "BOX_CONFIG_JSON=$BOX_CONFIG" >> "$ENV_LOCAL"
        echo "✓ Added BOX_CONFIG_JSON to $ENV_LOCAL"
    fi
fi

echo ""
echo "Setup complete! You can now use:"
echo "  export \$(grep -v '^#' $ENV_OUTPUT | xargs)"
echo "  python scripts/download_transcripts.py --count 50"
echo ""
echo "Or source the file:"
echo "  source $ENV_OUTPUT"
echo "  python scripts/download_transcripts.py --count 50"
